compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

packageExtensions:
  jest-playwright-preset@*:
    dependencies:
      playwright: 1.47.2
  markdown-it@*:
    dependencies:
      punycode: 2.3.0

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.5.3.cjs
