# Code generated by devtools/genmake, DO NOT EDIT.

.PHONY: $(BIN_DIR)/darwin-amd64/_all $(BIN_DIR)/linux-amd64/_all $(BIN_DIR)/linux-arm/_all $(BIN_DIR)/linux-arm64/_all

BIN_DIR=bin
GO_DEPS := Makefile.binaries.mk $(shell find . -path ./web/src -prune -o -path ./vendor -prune -o -path ./.git -prune -o -type f -name "*.go" -print) go.sum
GO_DEPS += migrate/migrations/ migrate/migrations/*.sql graphql2/graphqlapp/playground.html web/index.html graphql2/graphqlapp/slack.manifest.yaml
GO_DEPS += graphql2/mapconfig.go graphql2/maplimit.go graphql2/generated.go graphql2/models_gen.go

ifdef BUNDLE
	GO_DEPS += web/src/build/static/app.js
endif

GIT_COMMIT:=$(shell git rev-parse HEAD || echo '?')
GIT_TREE:=$(shell git diff-index --quiet HEAD -- && echo clean || echo dirty)
GIT_VERSION:=$(shell git describe --tags --dirty --match 'v*' || echo dev-$(shell date -u +"%Y%m%d%H%M%S"))
BUILD_DATE:=$(shell date -u +"%Y-%m-%dT%H:%M:%SZ")
BUILD_FLAGS=

export ZONEINFO:=$(shell go env GOROOT)/lib/time/zoneinfo.zip

LD_FLAGS+=-X github.com/target/goalert/version.gitCommit=$(GIT_COMMIT)
LD_FLAGS+=-X github.com/target/goalert/version.gitVersion=$(GIT_VERSION)
LD_FLAGS+=-X github.com/target/goalert/version.gitTreeState=$(GIT_TREE)
LD_FLAGS+=-X github.com/target/goalert/version.buildDate=$(BUILD_DATE)


$(BIN_DIR)/goalert: $(GO_DEPS) graphql2/mapconfig.go
	go build -o $@ ./cmd/goalert

$(BIN_DIR)/darwin-amd64/goalert: $(GO_DEPS) graphql2/mapconfig.go web/src/build/static/app.js
	GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags "$(LD_FLAGS)" -o $@ ./cmd/goalert

$(BIN_DIR)/linux-amd64/goalert: $(GO_DEPS) graphql2/mapconfig.go web/src/build/static/app.js
	GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "$(LD_FLAGS)" -o $@ ./cmd/goalert

$(BIN_DIR)/linux-arm/goalert: $(GO_DEPS) graphql2/mapconfig.go web/src/build/static/app.js
	GOOS=linux GOARCH=arm GOARM=7 go build -trimpath -ldflags "$(LD_FLAGS)" -o $@ ./cmd/goalert

$(BIN_DIR)/linux-arm64/goalert: $(GO_DEPS) graphql2/mapconfig.go web/src/build/static/app.js
	GOOS=linux GOARCH=arm64 go build -trimpath -ldflags "$(LD_FLAGS)" -o $@ ./cmd/goalert


$(BIN_DIR)/mockslack: $(GO_DEPS) 
	go build -o $@ ./devtools/mockslack/cmd/mockslack

$(BIN_DIR)/darwin-amd64/mockslack: $(GO_DEPS)  
	GOOS=darwin GOARCH=amd64 go build -trimpath  -o $@ ./devtools/mockslack/cmd/mockslack

$(BIN_DIR)/linux-amd64/mockslack: $(GO_DEPS)  
	GOOS=linux GOARCH=amd64 go build -trimpath  -o $@ ./devtools/mockslack/cmd/mockslack

$(BIN_DIR)/linux-arm/mockslack: $(GO_DEPS)  
	GOOS=linux GOARCH=arm GOARM=7 go build -trimpath  -o $@ ./devtools/mockslack/cmd/mockslack

$(BIN_DIR)/linux-arm64/mockslack: $(GO_DEPS)  
	GOOS=linux GOARCH=arm64 go build -trimpath  -o $@ ./devtools/mockslack/cmd/mockslack


$(BIN_DIR)/pgdump-lite: $(GO_DEPS) 
	go build -o $@ ./devtools/pgdump-lite/cmd/pgdump-lite

$(BIN_DIR)/darwin-amd64/pgdump-lite: $(GO_DEPS)  
	GOOS=darwin GOARCH=amd64 go build -trimpath  -o $@ ./devtools/pgdump-lite/cmd/pgdump-lite

$(BIN_DIR)/linux-amd64/pgdump-lite: $(GO_DEPS)  
	GOOS=linux GOARCH=amd64 go build -trimpath  -o $@ ./devtools/pgdump-lite/cmd/pgdump-lite

$(BIN_DIR)/linux-arm/pgdump-lite: $(GO_DEPS)  
	GOOS=linux GOARCH=arm GOARM=7 go build -trimpath  -o $@ ./devtools/pgdump-lite/cmd/pgdump-lite

$(BIN_DIR)/linux-arm64/pgdump-lite: $(GO_DEPS)  
	GOOS=linux GOARCH=arm64 go build -trimpath  -o $@ ./devtools/pgdump-lite/cmd/pgdump-lite


$(BIN_DIR)/procwrap: $(GO_DEPS) 
	go build -o $@ ./devtools/procwrap

$(BIN_DIR)/darwin-amd64/procwrap: $(GO_DEPS)  
	GOOS=darwin GOARCH=amd64 go build -trimpath  -o $@ ./devtools/procwrap

$(BIN_DIR)/linux-amd64/procwrap: $(GO_DEPS)  
	GOOS=linux GOARCH=amd64 go build -trimpath  -o $@ ./devtools/procwrap

$(BIN_DIR)/linux-arm/procwrap: $(GO_DEPS)  
	GOOS=linux GOARCH=arm GOARM=7 go build -trimpath  -o $@ ./devtools/procwrap

$(BIN_DIR)/linux-arm64/procwrap: $(GO_DEPS)  
	GOOS=linux GOARCH=arm64 go build -trimpath  -o $@ ./devtools/procwrap


$(BIN_DIR)/psql-lite: $(GO_DEPS) 
	go build -o $@ ./devtools/psql-lite

$(BIN_DIR)/darwin-amd64/psql-lite: $(GO_DEPS)  
	GOOS=darwin GOARCH=amd64 go build -trimpath  -o $@ ./devtools/psql-lite

$(BIN_DIR)/linux-amd64/psql-lite: $(GO_DEPS)  
	GOOS=linux GOARCH=amd64 go build -trimpath  -o $@ ./devtools/psql-lite

$(BIN_DIR)/linux-arm/psql-lite: $(GO_DEPS)  
	GOOS=linux GOARCH=arm GOARM=7 go build -trimpath  -o $@ ./devtools/psql-lite

$(BIN_DIR)/linux-arm64/psql-lite: $(GO_DEPS)  
	GOOS=linux GOARCH=arm64 go build -trimpath  -o $@ ./devtools/psql-lite


$(BIN_DIR)/resetdb: $(GO_DEPS) 
	go build -o $@ ./devtools/resetdb

$(BIN_DIR)/darwin-amd64/resetdb: $(GO_DEPS)  
	GOOS=darwin GOARCH=amd64 go build -trimpath  -o $@ ./devtools/resetdb

$(BIN_DIR)/linux-amd64/resetdb: $(GO_DEPS)  
	GOOS=linux GOARCH=amd64 go build -trimpath  -o $@ ./devtools/resetdb

$(BIN_DIR)/linux-arm/resetdb: $(GO_DEPS)  
	GOOS=linux GOARCH=arm GOARM=7 go build -trimpath  -o $@ ./devtools/resetdb

$(BIN_DIR)/linux-arm64/resetdb: $(GO_DEPS)  
	GOOS=linux GOARCH=arm64 go build -trimpath  -o $@ ./devtools/resetdb


$(BIN_DIR)/runjson: $(GO_DEPS) 
	go build -o $@ ./devtools/runjson

$(BIN_DIR)/darwin-amd64/runjson: $(GO_DEPS)  
	GOOS=darwin GOARCH=amd64 go build -trimpath  -o $@ ./devtools/runjson

$(BIN_DIR)/linux-amd64/runjson: $(GO_DEPS)  
	GOOS=linux GOARCH=amd64 go build -trimpath  -o $@ ./devtools/runjson

$(BIN_DIR)/linux-arm/runjson: $(GO_DEPS)  
	GOOS=linux GOARCH=arm GOARM=7 go build -trimpath  -o $@ ./devtools/runjson

$(BIN_DIR)/linux-arm64/runjson: $(GO_DEPS)  
	GOOS=linux GOARCH=arm64 go build -trimpath  -o $@ ./devtools/runjson


$(BIN_DIR)/sendit: $(GO_DEPS) 
	go build -o $@ ./devtools/sendit/cmd/sendit

$(BIN_DIR)/darwin-amd64/sendit: $(GO_DEPS)  
	GOOS=darwin GOARCH=amd64 go build -trimpath  -o $@ ./devtools/sendit/cmd/sendit

$(BIN_DIR)/linux-amd64/sendit: $(GO_DEPS)  
	GOOS=linux GOARCH=amd64 go build -trimpath  -o $@ ./devtools/sendit/cmd/sendit

$(BIN_DIR)/linux-arm/sendit: $(GO_DEPS)  
	GOOS=linux GOARCH=arm GOARM=7 go build -trimpath  -o $@ ./devtools/sendit/cmd/sendit

$(BIN_DIR)/linux-arm64/sendit: $(GO_DEPS)  
	GOOS=linux GOARCH=arm64 go build -trimpath  -o $@ ./devtools/sendit/cmd/sendit


$(BIN_DIR)/sendit-server: $(GO_DEPS) 
	go build -o $@ ./devtools/sendit/cmd/sendit-server

$(BIN_DIR)/darwin-amd64/sendit-server: $(GO_DEPS)  
	GOOS=darwin GOARCH=amd64 go build -trimpath  -o $@ ./devtools/sendit/cmd/sendit-server

$(BIN_DIR)/linux-amd64/sendit-server: $(GO_DEPS)  
	GOOS=linux GOARCH=amd64 go build -trimpath  -o $@ ./devtools/sendit/cmd/sendit-server

$(BIN_DIR)/linux-arm/sendit-server: $(GO_DEPS)  
	GOOS=linux GOARCH=arm GOARM=7 go build -trimpath  -o $@ ./devtools/sendit/cmd/sendit-server

$(BIN_DIR)/linux-arm64/sendit-server: $(GO_DEPS)  
	GOOS=linux GOARCH=arm64 go build -trimpath  -o $@ ./devtools/sendit/cmd/sendit-server


$(BIN_DIR)/sendit-token: $(GO_DEPS) 
	go build -o $@ ./devtools/sendit/cmd/sendit-token

$(BIN_DIR)/darwin-amd64/sendit-token: $(GO_DEPS)  
	GOOS=darwin GOARCH=amd64 go build -trimpath  -o $@ ./devtools/sendit/cmd/sendit-token

$(BIN_DIR)/linux-amd64/sendit-token: $(GO_DEPS)  
	GOOS=linux GOARCH=amd64 go build -trimpath  -o $@ ./devtools/sendit/cmd/sendit-token

$(BIN_DIR)/linux-arm/sendit-token: $(GO_DEPS)  
	GOOS=linux GOARCH=arm GOARM=7 go build -trimpath  -o $@ ./devtools/sendit/cmd/sendit-token

$(BIN_DIR)/linux-arm64/sendit-token: $(GO_DEPS)  
	GOOS=linux GOARCH=arm64 go build -trimpath  -o $@ ./devtools/sendit/cmd/sendit-token


$(BIN_DIR)/simpleproxy: $(GO_DEPS) 
	go build -o $@ ./devtools/simpleproxy

$(BIN_DIR)/darwin-amd64/simpleproxy: $(GO_DEPS)  
	GOOS=darwin GOARCH=amd64 go build -trimpath  -o $@ ./devtools/simpleproxy

$(BIN_DIR)/linux-amd64/simpleproxy: $(GO_DEPS)  
	GOOS=linux GOARCH=amd64 go build -trimpath  -o $@ ./devtools/simpleproxy

$(BIN_DIR)/linux-arm/simpleproxy: $(GO_DEPS)  
	GOOS=linux GOARCH=arm GOARM=7 go build -trimpath  -o $@ ./devtools/simpleproxy

$(BIN_DIR)/linux-arm64/simpleproxy: $(GO_DEPS)  
	GOOS=linux GOARCH=arm64 go build -trimpath  -o $@ ./devtools/simpleproxy


$(BIN_DIR)/waitfor: $(GO_DEPS) 
	go build -o $@ ./devtools/waitfor

$(BIN_DIR)/darwin-amd64/waitfor: $(GO_DEPS)  
	GOOS=darwin GOARCH=amd64 go build -trimpath  -o $@ ./devtools/waitfor

$(BIN_DIR)/linux-amd64/waitfor: $(GO_DEPS)  
	GOOS=linux GOARCH=amd64 go build -trimpath  -o $@ ./devtools/waitfor

$(BIN_DIR)/linux-arm/waitfor: $(GO_DEPS)  
	GOOS=linux GOARCH=arm GOARM=7 go build -trimpath  -o $@ ./devtools/waitfor

$(BIN_DIR)/linux-arm64/waitfor: $(GO_DEPS)  
	GOOS=linux GOARCH=arm64 go build -trimpath  -o $@ ./devtools/waitfor




$(BIN_DIR)/darwin-amd64/_all: $(BIN_DIR)/darwin-amd64/goalert-smoketest $(BIN_DIR)/darwin-amd64/goalert $(BIN_DIR)/darwin-amd64/mockslack $(BIN_DIR)/darwin-amd64/pgdump-lite $(BIN_DIR)/darwin-amd64/procwrap $(BIN_DIR)/darwin-amd64/psql-lite $(BIN_DIR)/darwin-amd64/resetdb $(BIN_DIR)/darwin-amd64/runjson $(BIN_DIR)/darwin-amd64/sendit $(BIN_DIR)/darwin-amd64/sendit-server $(BIN_DIR)/darwin-amd64/sendit-token $(BIN_DIR)/darwin-amd64/simpleproxy $(BIN_DIR)/darwin-amd64/waitfor

$(BIN_DIR)/darwin-amd64/goalert-smoketest: $(GO_DEPS)
	GOOS=darwin GOARCH=amd64 go test ./smoketest -c -o $@

$(BIN_DIR)/linux-amd64/_all: $(BIN_DIR)/linux-amd64/goalert-smoketest $(BIN_DIR)/linux-amd64/goalert $(BIN_DIR)/linux-amd64/mockslack $(BIN_DIR)/linux-amd64/pgdump-lite $(BIN_DIR)/linux-amd64/procwrap $(BIN_DIR)/linux-amd64/psql-lite $(BIN_DIR)/linux-amd64/resetdb $(BIN_DIR)/linux-amd64/runjson $(BIN_DIR)/linux-amd64/sendit $(BIN_DIR)/linux-amd64/sendit-server $(BIN_DIR)/linux-amd64/sendit-token $(BIN_DIR)/linux-amd64/simpleproxy $(BIN_DIR)/linux-amd64/waitfor

$(BIN_DIR)/linux-amd64/goalert-smoketest: $(GO_DEPS)
	GOOS=linux GOARCH=amd64 go test ./smoketest -c -o $@

$(BIN_DIR)/linux-arm/_all: $(BIN_DIR)/linux-arm/goalert-smoketest $(BIN_DIR)/linux-arm/goalert $(BIN_DIR)/linux-arm/mockslack $(BIN_DIR)/linux-arm/pgdump-lite $(BIN_DIR)/linux-arm/procwrap $(BIN_DIR)/linux-arm/psql-lite $(BIN_DIR)/linux-arm/resetdb $(BIN_DIR)/linux-arm/runjson $(BIN_DIR)/linux-arm/sendit $(BIN_DIR)/linux-arm/sendit-server $(BIN_DIR)/linux-arm/sendit-token $(BIN_DIR)/linux-arm/simpleproxy $(BIN_DIR)/linux-arm/waitfor

$(BIN_DIR)/linux-arm/goalert-smoketest: $(GO_DEPS)
	GOOS=linux GOARCH=arm GOARM=7 go test ./smoketest -c -o $@

$(BIN_DIR)/linux-arm64/_all: $(BIN_DIR)/linux-arm64/goalert-smoketest $(BIN_DIR)/linux-arm64/goalert $(BIN_DIR)/linux-arm64/mockslack $(BIN_DIR)/linux-arm64/pgdump-lite $(BIN_DIR)/linux-arm64/procwrap $(BIN_DIR)/linux-arm64/psql-lite $(BIN_DIR)/linux-arm64/resetdb $(BIN_DIR)/linux-arm64/runjson $(BIN_DIR)/linux-arm64/sendit $(BIN_DIR)/linux-arm64/sendit-server $(BIN_DIR)/linux-arm64/sendit-token $(BIN_DIR)/linux-arm64/simpleproxy $(BIN_DIR)/linux-arm64/waitfor

$(BIN_DIR)/linux-arm64/goalert-smoketest: $(GO_DEPS)
	GOOS=linux GOARCH=arm64 go test ./smoketest -c -o $@

$(BIN_DIR)/goalert-smoketest: $(GO_DEPS)
	go test ./smoketest -c -o $@



$(BIN_DIR)/goalert-darwin-amd64.tgz: $(BIN_DIR)/darwin-amd64/goalert
	rm -rf $(BIN_DIR)/goalert-darwin-amd64/
	mkdir -p $(BIN_DIR)/goalert-darwin-amd64/goalert/bin/
	cp  $(BIN_DIR)/darwin-amd64/goalert $(BIN_DIR)/goalert-darwin-amd64/goalert/bin/
	tar -czvf $(BIN_DIR)/goalert-darwin-amd64.tgz -C $(BIN_DIR)/goalert-darwin-amd64/ .

$(BIN_DIR)/goalert-linux-amd64.tgz: $(BIN_DIR)/linux-amd64/goalert
	rm -rf $(BIN_DIR)/goalert-linux-amd64/
	mkdir -p $(BIN_DIR)/goalert-linux-amd64/goalert/bin/
	cp  $(BIN_DIR)/linux-amd64/goalert $(BIN_DIR)/goalert-linux-amd64/goalert/bin/
	tar -czvf $(BIN_DIR)/goalert-linux-amd64.tgz -C $(BIN_DIR)/goalert-linux-amd64/ .

$(BIN_DIR)/goalert-linux-arm.tgz: $(BIN_DIR)/linux-arm/goalert
	rm -rf $(BIN_DIR)/goalert-linux-arm/
	mkdir -p $(BIN_DIR)/goalert-linux-arm/goalert/bin/
	cp  $(BIN_DIR)/linux-arm/goalert $(BIN_DIR)/goalert-linux-arm/goalert/bin/
	tar -czvf $(BIN_DIR)/goalert-linux-arm.tgz -C $(BIN_DIR)/goalert-linux-arm/ .

$(BIN_DIR)/goalert-linux-arm64.tgz: $(BIN_DIR)/linux-arm64/goalert
	rm -rf $(BIN_DIR)/goalert-linux-arm64/
	mkdir -p $(BIN_DIR)/goalert-linux-arm64/goalert/bin/
	cp  $(BIN_DIR)/linux-arm64/goalert $(BIN_DIR)/goalert-linux-arm64/goalert/bin/
	tar -czvf $(BIN_DIR)/goalert-linux-arm64.tgz -C $(BIN_DIR)/goalert-linux-arm64/ .



$(BIN_DIR)/integration-darwin-amd64.tgz: $(BIN_DIR)/darwin-amd64/goalert $(BIN_DIR)/darwin-amd64/mockslack $(BIN_DIR)/darwin-amd64/pgdump-lite $(BIN_DIR)/darwin-amd64/psql-lite $(BIN_DIR)/darwin-amd64/procwrap $(BIN_DIR)/darwin-amd64/simpleproxy $(BIN_DIR)/darwin-amd64/waitfor $(BIN_DIR)/integration/goalert/devtools $(BIN_DIR)/integration/goalert/.git $(BIN_DIR)/integration/goalert/COMMIT $(BIN_DIR)/integration/goalert/cypress $(BIN_DIR)/integration/goalert/cypress.json
	rm -rf $(BIN_DIR)/integration-darwin-amd64/
	mkdir -p $(BIN_DIR)/integration-darwin-amd64/goalert/bin/
	cp  $(BIN_DIR)/darwin-amd64/goalert $(BIN_DIR)/darwin-amd64/mockslack $(BIN_DIR)/darwin-amd64/pgdump-lite $(BIN_DIR)/darwin-amd64/psql-lite $(BIN_DIR)/darwin-amd64/procwrap $(BIN_DIR)/darwin-amd64/simpleproxy $(BIN_DIR)/darwin-amd64/waitfor $(BIN_DIR)/integration-darwin-amd64/goalert/bin/
	cp -r  $(BIN_DIR)/integration/goalert/devtools $(BIN_DIR)/integration/goalert/.git $(BIN_DIR)/integration/goalert/COMMIT $(BIN_DIR)/integration/goalert/cypress $(BIN_DIR)/integration/goalert/cypress.json $(BIN_DIR)/integration-darwin-amd64/goalert/
	tar -czvf $(BIN_DIR)/integration-darwin-amd64.tgz -C $(BIN_DIR)/integration-darwin-amd64/ .

$(BIN_DIR)/integration-linux-amd64.tgz: $(BIN_DIR)/linux-amd64/goalert $(BIN_DIR)/linux-amd64/mockslack $(BIN_DIR)/linux-amd64/pgdump-lite $(BIN_DIR)/linux-amd64/psql-lite $(BIN_DIR)/linux-amd64/procwrap $(BIN_DIR)/linux-amd64/simpleproxy $(BIN_DIR)/linux-amd64/waitfor $(BIN_DIR)/integration/goalert/devtools $(BIN_DIR)/integration/goalert/.git $(BIN_DIR)/integration/goalert/COMMIT $(BIN_DIR)/integration/goalert/cypress $(BIN_DIR)/integration/goalert/cypress.json
	rm -rf $(BIN_DIR)/integration-linux-amd64/
	mkdir -p $(BIN_DIR)/integration-linux-amd64/goalert/bin/
	cp  $(BIN_DIR)/linux-amd64/goalert $(BIN_DIR)/linux-amd64/mockslack $(BIN_DIR)/linux-amd64/pgdump-lite $(BIN_DIR)/linux-amd64/psql-lite $(BIN_DIR)/linux-amd64/procwrap $(BIN_DIR)/linux-amd64/simpleproxy $(BIN_DIR)/linux-amd64/waitfor $(BIN_DIR)/integration-linux-amd64/goalert/bin/
	cp -r  $(BIN_DIR)/integration/goalert/devtools $(BIN_DIR)/integration/goalert/.git $(BIN_DIR)/integration/goalert/COMMIT $(BIN_DIR)/integration/goalert/cypress $(BIN_DIR)/integration/goalert/cypress.json $(BIN_DIR)/integration-linux-amd64/goalert/
	tar -czvf $(BIN_DIR)/integration-linux-amd64.tgz -C $(BIN_DIR)/integration-linux-amd64/ .

$(BIN_DIR)/integration-linux-arm.tgz: $(BIN_DIR)/linux-arm/goalert $(BIN_DIR)/linux-arm/mockslack $(BIN_DIR)/linux-arm/pgdump-lite $(BIN_DIR)/linux-arm/psql-lite $(BIN_DIR)/linux-arm/procwrap $(BIN_DIR)/linux-arm/simpleproxy $(BIN_DIR)/linux-arm/waitfor $(BIN_DIR)/integration/goalert/devtools $(BIN_DIR)/integration/goalert/.git $(BIN_DIR)/integration/goalert/COMMIT $(BIN_DIR)/integration/goalert/cypress $(BIN_DIR)/integration/goalert/cypress.json
	rm -rf $(BIN_DIR)/integration-linux-arm/
	mkdir -p $(BIN_DIR)/integration-linux-arm/goalert/bin/
	cp  $(BIN_DIR)/linux-arm/goalert $(BIN_DIR)/linux-arm/mockslack $(BIN_DIR)/linux-arm/pgdump-lite $(BIN_DIR)/linux-arm/psql-lite $(BIN_DIR)/linux-arm/procwrap $(BIN_DIR)/linux-arm/simpleproxy $(BIN_DIR)/linux-arm/waitfor $(BIN_DIR)/integration-linux-arm/goalert/bin/
	cp -r  $(BIN_DIR)/integration/goalert/devtools $(BIN_DIR)/integration/goalert/.git $(BIN_DIR)/integration/goalert/COMMIT $(BIN_DIR)/integration/goalert/cypress $(BIN_DIR)/integration/goalert/cypress.json $(BIN_DIR)/integration-linux-arm/goalert/
	tar -czvf $(BIN_DIR)/integration-linux-arm.tgz -C $(BIN_DIR)/integration-linux-arm/ .

$(BIN_DIR)/integration-linux-arm64.tgz: $(BIN_DIR)/linux-arm64/goalert $(BIN_DIR)/linux-arm64/mockslack $(BIN_DIR)/linux-arm64/pgdump-lite $(BIN_DIR)/linux-arm64/psql-lite $(BIN_DIR)/linux-arm64/procwrap $(BIN_DIR)/linux-arm64/simpleproxy $(BIN_DIR)/linux-arm64/waitfor $(BIN_DIR)/integration/goalert/devtools $(BIN_DIR)/integration/goalert/.git $(BIN_DIR)/integration/goalert/COMMIT $(BIN_DIR)/integration/goalert/cypress $(BIN_DIR)/integration/goalert/cypress.json
	rm -rf $(BIN_DIR)/integration-linux-arm64/
	mkdir -p $(BIN_DIR)/integration-linux-arm64/goalert/bin/
	cp  $(BIN_DIR)/linux-arm64/goalert $(BIN_DIR)/linux-arm64/mockslack $(BIN_DIR)/linux-arm64/pgdump-lite $(BIN_DIR)/linux-arm64/psql-lite $(BIN_DIR)/linux-arm64/procwrap $(BIN_DIR)/linux-arm64/simpleproxy $(BIN_DIR)/linux-arm64/waitfor $(BIN_DIR)/integration-linux-arm64/goalert/bin/
	cp -r  $(BIN_DIR)/integration/goalert/devtools $(BIN_DIR)/integration/goalert/.git $(BIN_DIR)/integration/goalert/COMMIT $(BIN_DIR)/integration/goalert/cypress $(BIN_DIR)/integration/goalert/cypress.json $(BIN_DIR)/integration-linux-arm64/goalert/
	tar -czvf $(BIN_DIR)/integration-linux-arm64.tgz -C $(BIN_DIR)/integration-linux-arm64/ .


