platform: linux

image_resource:
  type: registry-image
  source: { repository: concourse/builder-task }

params:
  REPOSITORY: goalert/goalert
  TAG: latest
  CONTEXT: bin/goalert
  DOCKERFILE: goalert/devtools/ci/dockerfiles/goalert/Dockerfile

inputs:
  - name: goalert
  - name: bin

outputs:
  - name: image

run: { path: /usr/bin/build }
