FROM --platform=$BUILDPLATFORM goalert/build-env:go1.16.4-postgres13 AS binaries
ARG BUILDPLATFORM
COPY bin/linux-arm/goalert /linux/arm/v7/goalert
COPY bin/linux-arm64/goalert /linux/arm64/goalert
COPY bin/linux-amd64/goalert /linux/amd64/goalert

FROM alpine
ARG TARGETPLATFORM
RUN apk --no-cache add ca-certificates
ENV GOALERT_LISTEN :8081
EXPOSE 8081
CMD ["/usr/bin/goalert"]

COPY --from=binaries /$TARGETPLATFORM/goalert /usr/bin/goalert
RUN /usr/bin/goalert self-test
