FROM multiarch/qemu-user-static:x86_64-arm AS qemu

FROM scratch AS extract
ADD bin/goalert-linux-arm.tgz /files/

FROM arm32v7/alpine
COPY --from=qemu /usr/bin/qemu-arm-static /usr/bin/
RUN apk --no-cache add tzdata ca-certificates
ENV GOALERT_LISTEN :8081
CMD ["/usr/bin/goalert"]

COPY --from=extract /files/goalert/bin/goalert /usr/bin/goalert
