// Code generated by "stringer -type SourceType"; DO NOT EDIT.

package permission

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SourceTypeNotificationCallback-0]
	_ = x[SourceTypeIntegrationKey-1]
	_ = x[SourceTypeAuthProvider-2]
	_ = x[SourceTypeContactMethod-3]
	_ = x[SourceTypeHeartbeat-4]
	_ = x[SourceTypeNotificationChannel-5]
	_ = x[SourceTypeCalendarSubscription-6]
	_ = x[SourceTypeGQLAPIKey-7]
}

const _SourceType_name = "SourceTypeNotificationCallbackSourceTypeIntegrationKeySourceTypeAuthProviderSourceTypeContactMethodSourceTypeHeartbeatSourceTypeNotificationChannelSourceTypeCalendarSubscriptionSourceTypeGQLAPIKey"

var _SourceType_index = [...]uint8{0, 30, 54, 76, 99, 118, 147, 177, 196}

func (i SourceType) String() string {
	if i < 0 || i >= SourceType(len(_SourceType_index)-1) {
		return "SourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SourceType_name[_SourceType_index[i]:_SourceType_index[i+1]]
}
