#!/bin/sh
set -e

SCRIPT_DIR=$(dirname $0)

(cd "$SCRIPT_DIR/../.." && make bin/tools/k6)

export K6_WEB_DASHBOARD=true
# experimental_enhanced is required so we can write our tests in TypeScript
exec "$SCRIPT_DIR/../../bin/tools/k6" run --compatibility-mode=experimental_enhanced $@
