version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/web/src/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "cypress"
          version_requirement: "<=3.6.1"
      - match:
          dependency_name: "react-infinite-scroll-component"
          version_requirement: "<=5.0.3"

  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
