// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: pkg/sysapi/sysapi.proto

package sysapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsersWithoutAuthProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersWithoutAuthProviderRequest) Reset() {
	*x = UsersWithoutAuthProviderRequest{}
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersWithoutAuthProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersWithoutAuthProviderRequest) ProtoMessage() {}

func (x *UsersWithoutAuthProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersWithoutAuthProviderRequest.ProtoReflect.Descriptor instead.
func (*UsersWithoutAuthProviderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sysapi_sysapi_proto_rawDescGZIP(), []int{0}
}

func (x *UsersWithoutAuthProviderRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type SetAuthSubjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *AuthSubject           `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAuthSubjectRequest) Reset() {
	*x = SetAuthSubjectRequest{}
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAuthSubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAuthSubjectRequest) ProtoMessage() {}

func (x *SetAuthSubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAuthSubjectRequest.ProtoReflect.Descriptor instead.
func (*SetAuthSubjectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sysapi_sysapi_proto_rawDescGZIP(), []int{1}
}

func (x *SetAuthSubjectRequest) GetSubject() *AuthSubject {
	if x != nil {
		return x.Subject
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_pkg_sysapi_sysapi_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SetAuthSubjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAuthSubjectResponse) Reset() {
	*x = SetAuthSubjectResponse{}
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAuthSubjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAuthSubjectResponse) ProtoMessage() {}

func (x *SetAuthSubjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAuthSubjectResponse.ProtoReflect.Descriptor instead.
func (*SetAuthSubjectResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sysapi_sysapi_proto_rawDescGZIP(), []int{3}
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sysapi_sysapi_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sysapi_sysapi_proto_rawDescGZIP(), []int{5}
}

type AuthSubjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSubjectsRequest) Reset() {
	*x = AuthSubjectsRequest{}
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSubjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSubjectsRequest) ProtoMessage() {}

func (x *AuthSubjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSubjectsRequest.ProtoReflect.Descriptor instead.
func (*AuthSubjectsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sysapi_sysapi_proto_rawDescGZIP(), []int{6}
}

func (x *AuthSubjectsRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *AuthSubjectsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AuthSubject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	SubjectId     string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSubject) Reset() {
	*x = AuthSubject{}
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSubject) ProtoMessage() {}

func (x *AuthSubject) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sysapi_sysapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSubject.ProtoReflect.Descriptor instead.
func (*AuthSubject) Descriptor() ([]byte, []int) {
	return file_pkg_sysapi_sysapi_proto_rawDescGZIP(), []int{7}
}

func (x *AuthSubject) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthSubject) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *AuthSubject) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

var File_pkg_sysapi_sysapi_proto protoreflect.FileDescriptor

const file_pkg_sysapi_sysapi_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/sysapi/sysapi.proto\x12\n" +
	"goalert.v1\"B\n" +
	"\x1fUsersWithoutAuthProviderRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"J\n" +
	"\x15SetAuthSubjectRequest\x121\n" +
	"\asubject\x18\x01 \x01(\v2\x17.goalert.v1.AuthSubjectR\asubject\"D\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\x18\n" +
	"\x16SetAuthSubjectResponse\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x14\n" +
	"\x12DeleteUserResponse\"O\n" +
	"\x13AuthSubjectsRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"f\n" +
	"\vAuthSubject\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId2\xe3\x02\n" +
	"\x06SysAPI\x12L\n" +
	"\fAuthSubjects\x12\x1f.goalert.v1.AuthSubjectsRequest\x1a\x17.goalert.v1.AuthSubject\"\x000\x01\x12M\n" +
	"\n" +
	"DeleteUser\x12\x1d.goalert.v1.DeleteUserRequest\x1a\x1e.goalert.v1.DeleteUserResponse\"\x00\x12a\n" +
	"\x18UsersWithoutAuthProvider\x12+.goalert.v1.UsersWithoutAuthProviderRequest\x1a\x14.goalert.v1.UserInfo\"\x000\x01\x12Y\n" +
	"\x0eSetAuthSubject\x12!.goalert.v1.SetAuthSubjectRequest\x1a\".goalert.v1.SetAuthSubjectResponse\"\x00B&Z$github.com/target/goalert/pkg/sysapib\x06proto3"

var (
	file_pkg_sysapi_sysapi_proto_rawDescOnce sync.Once
	file_pkg_sysapi_sysapi_proto_rawDescData []byte
)

func file_pkg_sysapi_sysapi_proto_rawDescGZIP() []byte {
	file_pkg_sysapi_sysapi_proto_rawDescOnce.Do(func() {
		file_pkg_sysapi_sysapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_sysapi_sysapi_proto_rawDesc), len(file_pkg_sysapi_sysapi_proto_rawDesc)))
	})
	return file_pkg_sysapi_sysapi_proto_rawDescData
}

var file_pkg_sysapi_sysapi_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_sysapi_sysapi_proto_goTypes = []any{
	(*UsersWithoutAuthProviderRequest)(nil), // 0: goalert.v1.UsersWithoutAuthProviderRequest
	(*SetAuthSubjectRequest)(nil),           // 1: goalert.v1.SetAuthSubjectRequest
	(*UserInfo)(nil),                        // 2: goalert.v1.UserInfo
	(*SetAuthSubjectResponse)(nil),          // 3: goalert.v1.SetAuthSubjectResponse
	(*DeleteUserRequest)(nil),               // 4: goalert.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),              // 5: goalert.v1.DeleteUserResponse
	(*AuthSubjectsRequest)(nil),             // 6: goalert.v1.AuthSubjectsRequest
	(*AuthSubject)(nil),                     // 7: goalert.v1.AuthSubject
}
var file_pkg_sysapi_sysapi_proto_depIdxs = []int32{
	7, // 0: goalert.v1.SetAuthSubjectRequest.subject:type_name -> goalert.v1.AuthSubject
	6, // 1: goalert.v1.SysAPI.AuthSubjects:input_type -> goalert.v1.AuthSubjectsRequest
	4, // 2: goalert.v1.SysAPI.DeleteUser:input_type -> goalert.v1.DeleteUserRequest
	0, // 3: goalert.v1.SysAPI.UsersWithoutAuthProvider:input_type -> goalert.v1.UsersWithoutAuthProviderRequest
	1, // 4: goalert.v1.SysAPI.SetAuthSubject:input_type -> goalert.v1.SetAuthSubjectRequest
	7, // 5: goalert.v1.SysAPI.AuthSubjects:output_type -> goalert.v1.AuthSubject
	5, // 6: goalert.v1.SysAPI.DeleteUser:output_type -> goalert.v1.DeleteUserResponse
	2, // 7: goalert.v1.SysAPI.UsersWithoutAuthProvider:output_type -> goalert.v1.UserInfo
	3, // 8: goalert.v1.SysAPI.SetAuthSubject:output_type -> goalert.v1.SetAuthSubjectResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_sysapi_sysapi_proto_init() }
func file_pkg_sysapi_sysapi_proto_init() {
	if File_pkg_sysapi_sysapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_sysapi_sysapi_proto_rawDesc), len(file_pkg_sysapi_sysapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_sysapi_sysapi_proto_goTypes,
		DependencyIndexes: file_pkg_sysapi_sysapi_proto_depIdxs,
		MessageInfos:      file_pkg_sysapi_sysapi_proto_msgTypes,
	}.Build()
	File_pkg_sysapi_sysapi_proto = out.File
	file_pkg_sysapi_sysapi_proto_goTypes = nil
	file_pkg_sysapi_sysapi_proto_depIdxs = nil
}
