name: Actions Runner Controller Demo
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
      - run: echo "🎉 This job uses runner scale set runners!"
