name: labeler v2

on:
  pull_request:
    types: ['opened', 'ready_for_review', 'reopened', 'synchronize']

jobs:
  labeler:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    name: Label the PR size
    steps:
      - uses: actions/checkout@v3
      - name: Run labeler script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.number }}
        run: ./devtools/scripts/github-set-pr-label.sh
