name: labeler
on:
  pull_request:
    types: ['opened', 'ready_for_review', 'reopened', 'synchronize']

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    name: Label the PR size
    steps:
      - uses: actions/checkout@v6
        with: # checkout the base branch, where we run the script from
          path: base
          fetch-depth: 0

      # fetch the PR merge commit as a Git object, but do not check it out
      - name: Fetch PR merge ref
        working-directory: base
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          git fetch --no-tags origin \
            "refs/pull/${PR_NUMBER}/merge:refs/remotes/pull/${PR_NUMBER}/merge"

      - name: Run labeler script from base
        working-directory: base
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          FAIL_IF_XL: '1'
          MAIN_BRANCH: ${{ github.event.pull_request.base.ref }}
          DIFF_HEAD_REF: refs/remotes/pull/${{ github.event.number }}/merge
        run: devtools/scripts/github-set-pr-label.sh
